owner: H2O-ME
repo: upptime
user-agent: H2O-ME
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
  - name: Bing
    url: https://www.bing.com
    type: globalping # Use the Globalping platform to run the check
    location: california # Location to run the check from. Default is "World"
status-website: # Status website (optional)
  baseUrl: /repo
  name: Upptime # Status website title
